# Generated by Django 5.1.3 on 2024-11-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_booking.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Customer', 'Customer'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
