# Generated by Django 5.1.3 on 2024-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0003_remove_bus_owner_bus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='features',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='user',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_id',
            field=models.CharField(default=502, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='bus_id',
            field=models.CharField(default=23, max_length=7),
            preserve_default=False,
        ),
    ]
