# Generated by Django 5.1.3 on 2024-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0004_remove_bus_features_remove_bus_user_bus_bus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bus_id',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
