# Generated by Django 5.1.3 on 2024-12-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busmodel', '0002_booking_payment_reference_alter_booking_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='schedule',
            new_name='schedule_id',
        ),
    ]
