# Generated by Django 5.1.3 on 2024-12-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busmodel', '0003_rename_schedule_seat_schedule_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='schedule_id',
            new_name='schedule',
        ),
    ]
