# Generated by Django 5.1.3 on 2024-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmodel', '0004_rename_schedule_id_seat_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.JSONField(default=list),
        ),
    ]
