# Generated by Django 5.1.3 on 2024-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmodel', '0006_remove_booking_seat_numbers_booking_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.JSONField(default=list),
        ),
    ]
